// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tgevogmyakjacagkjkrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnZXZvZ215YWtqYWNhZ2tqa3JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxNTU3NjUsImV4cCI6MjA4NzczMTc2NX0.34BMwWj2_Y9qadh6qBUICuDtnZV87uLt53sSH_gKMaM";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);